config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  resources :users do
    collection do
      get :index
    end
    member do
      post :toggle_inscriptions_manager
    end
  end

  resources :equipiers
  resources :equipages do
    collection do
      get :rechercher
      get :recap
    end
    resources :equipiers
  end

  get '/' => "home#index", :as => :home
  root :to => "home#index"

end

app/models/equipage.rb
class Equipage < ApplicationRecord
  include Commun

  has_many :equipiers, dependent: :destroy
  belongs_to :user

  mount_uploader :carte_grise, CarteGriseUploader

  acts_as_xlsx

  validates :numero, uniqueness: {message: " : ce numéro d'équipage est déjà réservé ! <br \>Choisissez-en un autre ou contactez Aline"}

  # Recherche les objets avec une référence ou une désignation contenant le mot-clé recherché
  def self.contenant(terme)
    terme = full_text(terme)

    joins(:equipiers).
    where("numero LIKE ? OR immatriculation LIKE ? OR equipiers.nom LIKE ? OR equipiers.prenom LIKE ?", terme, terme, terme, terme)
  end

  # Recherche les objets relatifs à la recherche (passée en paramètre)
  def self.filtre_par(terme)
    order(id: :desc).
    contenant(terme).
    group(:id)
  end

  def self.tous
    all.avec_equipiers
  end
	
  def self.avec_equipiers
    select(:id).
    select("max(numero) AS numero").
    select("max(conducteur.prenom)").select("max(conducteur.nom)").
    select("max(passager.prenom)").select("max(passager.nom)").
    joins("LEFT JOIN equipiers conducteur ON conducteur.equipage_id = equipages.id AND conducteur.conducteur").
    joins("LEFT JOIN equipiers passager ON passager.equipage_id = equipages.id AND NOT passager.conducteur").
    group(:id).
    order(:numero).
    order("max(conducteur.nom)")
  end

  def self.avec_numero_ou_conducteur
    select("*").
    includes(:equipiers).
    where("equipages.numero IS NOT NULL OR equipiers.conducteur OR equipiers.id IS NULL").
    order(:numero).
    order("equipiers.nom")
  end

  def self.avec_equipiers_csv
    select("equipages.*").
    select("equipiers.*").
    joins("LEFT JOIN equipiers ON equipiers.equipage_id = equipages.id").
    order(numero: :asc)
  end

end

app/controllers/equipages_controller.rb
class EquipagesController < CrudController
  include RenderCsv

  #custom_actions :resource => [:cloner]

  def attrs_for_form
[:numero, :type_puissance, :carte_grise, :carte_grise_titulaire, :carte_grise_date_emission, :premiere_mise_en_circ, :immatriculation, :cie_assurance]
  end

  before_action :set_equipage, only: [:index]

  # GET /equipages
  def index
    if (@filtre && !@filtre.empty?)
      # Affiche les objets résultant d'un filtrage
      equipages = Equipage.filtre_par(@filtre)

    # listage d'un élément spécifié par son id
    elsif (@equipage)
      equipages = Equipage.where(id: @equipage)

    elsif current_user.admin? || current_user.inscription_manager?
      equipages = Equipage.tous
      
    else
      equipages = Equipage.where(user_id: current_user)

    end
    
    respond_to do |format|
      format.html {
        @equipages = equipages.page(@page)
      }
      format.xlsx
    end
  end

  # POST /equipages
  def create
    @equipage = Equipage.new(equipage_params)
    @equipage.user = current_user

    super(notice: t(:equipage_cree))
  end

  # GET /equipages/recap
  def recap

    respond_to do |format|
      format.html {
        @equipages = Equipage.avec_equipiers
        # recap.html.slim
      }
      format.csv { 
        @equipages = Equipage.avec_equipiers_csv
        render plain: to_csv(
          @equipages.all,
          [
            :numero,
            :type_puissance,
            :carte_grise_titulaire,
            :carte_grise_date_emission,
            :premiere_mise_en_circ,
            :immatriculation,
            :cie_assurance,
            :nom,
            :prenom,
            :rue,
            :cp,
            :ville,
            :telephone_fixe,
            :telephone_portable,
            :email,
            :profession,
            :date_naissance,
            :lieu_naissance,
            :nationalite,
            :permis_conduire_num,
            :passeport_num,
            :passeport_date_delivrance,
            :passeport_lieu_delivrance,
            :passeport_date_validite,
            :groupe_sanguin,
            :nom_prenom_a_prevenir,
            :tel_a_prevenir,
            :taille_t_shirt
          ]
        )
      }
     end
  end

private
  # Only allow a trusted parameter "white list" through.
  def equipage_params
    params.require(:equipage).permit(:numero, :type_puissance, 
      :carte_grise, :carte_grise_titulaire, :carte_grise_date_emission, :premiere_mise_en_circ, :immatriculation, 
      :cie_assurance,
      :user_id)
  end

  def set_equipage
    @equipage = Equipage.find(params[:id]) unless params[:id].blank?
  end

end

app/helpers/equipages_helper.rb
module EquipagesHelper
end

app/views/equipages/_form.html.slim
= simple_form_for @equipage do |f|
  = afficher_erreurs(@equipage, 'la modification de cet équipage :')
  
  = f.input :numero, input_html: {title: "Uniquement pour les participants au DERNIER raid 2016 : si vous souhaitez conserver votre numéro de véhicule, indiquez-le. Autres cas : laissez ce champ vide"}
  = f.input :type_puissance
  = link_to(image_tag("icone_pdf.png"), @equipage.carte_grise.url) if @equipage.carte_grise? &&  (can? :edit, @equipage)
  = f.input :carte_grise, as: :file
  = f.input :carte_grise_titulaire
  = f.input :carte_grise_date_emission, start_year: Date.today.year - 80, end_year: Date.today.year, include_blank: true
  = f.input :premiere_mise_en_circ, start_year: Date.today.year - 80, end_year: Date.today.year, include_blank: true
  = f.input :immatriculation
  = f.input :cie_assurance    

  .actions = f.submit t(:save_equipage)

app/views/equipages/_liste.html.slim
- equipage = resource
- conducteur = equipage.equipiers.conducteur.take if equipage.equipiers.conducteur.exists?
- passager   = equipage.equipiers.passager.take   if equipage.equipiers.passager.exists?

tr
  td = equipage.numero

  td = image_tag(conducteur.photo.thumb_s.url) if conducteur && conducteur.photo? 
  td = conducteur.prenom_nom if conducteur
    
  td = image_tag(passager.photo.thumb_s.url) if passager && passager.photo?
  td = passager.prenom_nom if passager

  td = link_to '', equipage_equipiers_path(equipage), class: :edit
  td = link_to '', equipage_path(equipage), class: :loupe
  td = link_to '', edit_equipage_path(equipage), class: :edit if (can? :edit, equipage)
  td = link_to '', equipage, data: {:confirm => 'Etes-vous sûr(e) ?'}, :method => :delete, class: :bin if (can? :destroy, equipage)

app/views/equipages/edit.html.slim
- content_for :nav do
  li = link_to 'Accueil', home_path
  li = link_to 'Annuler', :back

- content_for :page_title do
  = "Modifier/compléter l'équipage #{@equipage.numero}"

= render 'form'

app/views/equipages/index.html.slim
- content_for :nav do
  li = link_to 'Accueil', home_path
  li = link_to 'Nouveau véhicule', new_equipage_path
  li = link_to 'Tous les véhicules', equipages_path if inscription_manager_logged_in?
  li = link_to 'Voir le récap', recap_equipages_path if (can? :export, Equipage)

- content_for :page_title do
  ' Liste des équipages/véhicules

= filtrer('', 'Filtrer par nom, numéro, immat.&nbsp;:', :filtre, "Saisissez qq car. du véhicule ou de l'équipier") if inscription_manager_logged_in?
= will_paginate @equipages

table.list
  thead
    tr
      th.centre Numéro d'équipage
      th
      th.centre Conducteur
      th
      th.centre Passager
      th.centre.action Déclarer / Lister les équipiers

      th.centre Détails de votre véhicule
      th.centre.action Modifier / Compléter le descriptif de votre véhicule
      th.centre.action Supprimer

  tbody#liste_body
    = render partial: "liste", collection: @equipages, as: :resource

= link_to 'Exporter en Excel', equipages_path(format: :xlsx), class: :bouton if (can? :export, Equipage)

app/views/equipages/recap.html.slim
- content_for :nav do
  li = link_to 'Accueil', home_path
  li = link_to 'Tous les véhicules', equipages_path

- content_for :page_title do
  ' Liste des véhicules/équipiers

table.list
  thead
    tr
      th.centre{rowspan=2} = t(:nom)
      th.centre{rowspan=2} = t(:prenom)
      th.centre{rowspan=2} = t(:photo)
      th.centre{rowspan=2} = t(:ville)
      th.centre{rowspan=2} = t(:telephone_fixe)
      th.centre{rowspan=2} = t(:telephone_portable)
      th.centre{rowspan=2} = t(:email)
      th.centre{rowspan=2} = t(:date_naissance)	 
      th.centre{rowspan=2} = t(:nationalite) 
      th.centre{colspan=2} permis
      th.centre{colspan=3} passeport
      th.centre{rowspan=2} = t(:groupe_sanguin)
      th.centre{colspan=2} en cas de pb
      th.centre{rowspan=2} = t(:taille_t_shirt)
    tr
      th.centre = t(:permis_conduire_num)		 
      th.centre = t(:permis_conduire)
      th.centre = t(:passeport_num) 
      th.centre = t(:passeport)
      th.centre = t(:passeport_date_validite)
      th.centre = t(:nom_prenom_a_prevenir)		 
      th.centre = t(:tel_a_prevenir)

  - @equipages.each do |equipage|
    tbody
      tr.equipage
        th{colspan=2} = "Equipage #{equipage.numero}"
        - if equipage.carte_grise?
          th{colspan=98} = link_to(image_tag("icone_pdf.png"), equipage.carte_grise.url)
        - else
          th.warning{colspan=98} Carte grise non fournie !
           
      - equipage.equipiers.each do |equipier|
        tr
          td = equipier.nom
          td = equipier.prenom
          - if equipier.photo?
            td = image_tag(equipier.photo.thumb_s.url)
          - else
            td.warning non définie
          td = equipier.ville
          td = equipier.telephone_fixe
          td = equipier.telephone_portable
          td = equipier.email
          td = equipier.date_naissance	 
          td = equipier.nationalite
          td = equipier.permis_conduire_num		 
          - if equipier.permis_conduire?
            td = link_to(image_tag("icone_pdf.png"), equipier.permis_conduire.url)
          - else
            td.warning non fourni !
          td = equipier.passeport_num 
          - if equipier.passeport?
            td = link_to(image_tag("icone_pdf.png"), equipier.passeport.url)
          - else
            td.warning non fourni !
          td = equipier.passeport_date_validite
          td = equipier.groupe_sanguin
          td = equipier.nom_prenom_a_prevenir		 
          td = equipier.tel_a_prevenir
          td = equipier.taille_t_shirt

= link_to('Exporter le récap au format CSV', recap_equipages_path(format: :csv, alea: rand(10000)), {class: :bouton})