config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  resources :users do
    collection do
      get :index
    end
    member do
      post :toggle_inscriptions_manager
    end
  end

  resources :equipiers
  resources :equipages do
    collection do
      get :rechercher
      get :recap
    end
    resources :equipiers
  end

  get '/' => "home#index", :as => :home
  root :to => "home#index"

end

app/models/equipier.rb
class Equipier < ApplicationRecord
  include Commun

  belongs_to :equipage
  belongs_to :user
  
  mount_uploader :photo, PhotoUploader
  mount_uploader :permis_conduire, PermisConduireUploader
  mount_uploader :passeport, PasseportUploader
  
  before_save :nom_en_majuscules, :prenom_avec_initiale_maj

  validates_length_of :telephone_fixe, maximum: 15, allow_blank: true
  validates_length_of :telephone_portable, maximum: 15, allow_blank: true
  validates_length_of :groupe_sanguin, maximum: 50
  validates_length_of :tel_a_prevenir, maximum: 15, allow_blank: true

  # Recherche les objets avec une référence ou une désignation contenant le mot-clé recherché
  def self.contenant(terme)
    terme = full_text(terme)

    where("nom LIKE ?", terme)
  end

  # Recherche les objets relatifs à la recherche (passée en paramètre)
  def self.filtre_par(terme)
    select("*").
    order(id: :desc).
    contenant(terme)
  end
  
  def self.conducteur
   where(conducteur: true)
  end

  def self.passager
    where(conducteur: false)
  end

  def prenom_nom
    self.prenom + " " + self.nom
  end

protected

  def nom_en_majuscules
    self.nom = nom.upcase
  end

  def prenom_avec_initiale_maj
    self.prenom = prenom.capitalize
  end

end

app/controllers/equipiers_controller.rb
class EquipiersController < CrudController
  #custom_actions :resource => [:cloner]

  def attrs_for_index
    [:nom, :prenom, :telephone_fixe, :telephone_portable, :email]
  end

  def attrs_for_form	
[:nom, :prenom, :rue, :cp, :ville, :telephone_fixe, :telephone_portable, :email, :profession, :date_naissance, :lieu_naissance, :nationalite, :permis_conduire_num, :permis_conduire, :passeport_num, :passeport, :passeport_date_delivrance, :passeport_lieu_delivrance, :passeport_date_validite, :groupe_sanguin, :nom_prenom_a_prevenir, :tel_a_prevenir, :equipage_id]
  end

  before_action :set_equipier, only: [:update]
  before_action :set_equipage, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /equipiers
  def index
    if (@filtre && !@filtre.empty?)
      # Affiche les objets résultant d'un filtrage
      equipiers = Equipier.filtre_par(@filtre)

    # listage des équipiers d'un équipage donné
    elsif (@equipage)
      equipiers = @equipage.equipiers.order(conducteur: :desc)

    # listage d'un élément spécifié par son id
    elsif (@equipier)
      equipiers = Equipier.where(id: @equipier.id)

    else
      equipiers = Equipier.all

    end

    @equipiers = equipiers.page(@page)
  end

  # GET /equipier
  def new
    @equipier = @equipage.equipiers.new
    super
  end

  # POST /equipiers
  def create
    @equipier = @equipage.equipiers.new(equipier_params)
    @equipier.user = current_user

    super(notice: 'Equipier ajouté.') {
      equipage_equipiers_path(@equipage)
    }
  end

  # PATCH/PUT /equipage/x/equipiers/1
  def update
    super {
      equipage_equipiers_path(@equipage)
    }
  end

  # DELETE /equipage/x/equipiers/1
  def destroy
    super {
      equipage_equipiers_path(@equipage)
    }
  end

private
  # Only allow a trusted parameter "white list" through.
  def equipier_params
    params.require(:equipier).permit(:conducteur, :nom, :prenom, :photo,
	:rue, :cp, :ville, 
	:telephone_fixe, :telephone_portable, :email, 
	:profession, 
	:date_naissance, :lieu_naissance, :nationalite, 
	:permis_conduire_num, :permis_conduire, 
	:passeport_num, :passeport, :passeport_date_delivrance, :passeport_lieu_delivrance, :passeport_date_validite, 
	:groupe_sanguin, 
        :taille_t_shirt,
	:nom_prenom_a_prevenir, :tel_a_prevenir, 
	:equipage_id, 
	:user_id)
  end

  def set_equipier
    @equipier = Equipier.find(params[:id])
  end

  def set_equipage
    @equipage = Equipage.find(params[:equipage_id]) unless params[:equipage_id].blank?
    unless @equipage
      @equipage = Equipage.find(params[:equipier][:equipage_id]) unless params[:equipier][:equipage_id].blank?
    end
  end

end

app/helpers/equipiers_helper.rb
module EquipiersHelper
end

app/views/equipiers/_form.html.slim
= simple_form_for [@equipage, @equipier] do |f|
  = afficher_erreurs(@equipier, 'la modification de cet équipier :')
  
  fieldset
    legend = "Equipier pour l'équipage numéro #{@equipier.equipage.numero}"
    = link_to(image_tag(@equipier.photo.small.url), @equipier.photo.url) if @equipier.photo?
    div
      = label_tag ""
      = f.collection_radio_buttons :conducteur, [[true, 'Conducteur'] ,[false, 'Passager']], :first, :last
    = f.input :nom
    = f.input :prenom
    = f.input :photo, as: :file
    = f.input :rue
    = f.input :cp
    = f.input :ville
    = f.input :telephone_fixe, as: :tel
    = f.input :telephone_portable, as: :tel
    = f.input :email, as: :email
    = f.input :profession
    = f.input :date_naissance, start_year: Date.today.year - 90, end_year: Date.today.year - 18, include_blank: true
    = f.input :lieu_naissance
    = f.input :nationalite
    
    div
      = f.label :taille_t_shirt
      = f.select :taille_t_shirt, ["S", "M", "L", "XL", "XXL", "XXXL"], include_blank: true
      
  fieldset
    legend Permis de conduire
    = f.input :permis_conduire_num
    = link_to(image_tag("icone_pdf.png"), @equipier.permis_conduire.url) if @equipier.permis_conduire? &&  (can? :edit, @equipier)
    = f.input :permis_conduire, as: :file

  fieldset
    legend Passeport
    = f.input :passeport_num
    = link_to(image_tag("icone_pdf.png"), @equipier.passeport.url) if @equipier.passeport? &&  (can? :edit, @equipier)
    = f.input :passeport, as: :file
    = f.input :passeport_date_delivrance, start_year: Date.today.year - 10, end_year: Date.today.year, include_blank: true
    = f.input :passeport_lieu_delivrance
    = f.input :passeport_date_validite, start_year: Date.today.year, end_year: Date.today.year + 10, include_blank: true
    = f.input :groupe_sanguin

  fieldset
    legend Personne à prévenir en cas de problème
    = f.input :nom_prenom_a_prevenir
    = f.input :tel_a_prevenir, as: :tel
  
  .actions = f.submit t(:save_equipier)

app/views/equipiers/edit.html.slim
- content_for :nav do
  li = link_to 'Accueil', home_path
  li = link_to 'Annuler', :back

- content_for :page_title do
  = "Modifier l'équipier #{@equipier.prenom_nom}"

= render 'form' if  (can? :edit, @equipier)

app/views/equipiers/index.html.slim
- content_for :nav do
  li = link_to 'Accueil', home_path
  li = link_to 'Nouvel équipier', new_equipage_equipier_path(@equipage)
  li = link_to "Voir le véhicule", equipages_path(id: @equipage)
  li = link_to 'Tous les véhicules', equipages_path if inscription_manager_logged_in?

- content_for :page_title do
  ' Les équipiers du véhicule #{@equipage.numero}

= will_paginate @equipiers

table.list
  thead
    tr
      th.centre = t(:conducteur)
      th.centre
      th.centre = t(:nom)
      th.centre = t(:prenom)
      th.centre = t(:telephone_portable)
      th.centre = t(:email)
      th Détails
      th.action Modifier / Compléter l'équipier
      th.action Supprimer

  tbody
    - @equipiers.each do |equipier|
      tr
        td.centre = affiche_booleen(equipier.conducteur)
        td = image_tag(equipier.photo.thumb_s.url) if equipier.photo?
        td = equipier.nom
        td = equipier.prenom
        td = equipier.telephone_portable
        td = equipier.email
        td = link_to '', equipage_equipier_path(@equipage, equipier), class: :loupe
        td = link_to '', edit_equipage_equipier_path(@equipage, equipier), class: :edit if (can? :edit, equipier)
        td = link_to '', equipage_equipier_path(@equipage, equipier), data: {:confirm => 'Etes-vous sûr(e) ?'}, :method => :delete, class: :bin if (can? :destroy, equipier)

app/views/equipiers/show.html.slim
- content_for :nav do
  li = link_to 'Retour', :back
  li = link_to 'Gestion des utilisateurs', users_path if (can? :manage, User)

- content_for :page_title do
  = t("show_equipier")

table
  tr
    th.centre Info
    th.centre Valeur
  tr
    th = t(:conducteur)
    td = @equipier.conducteur ? "Oui" : "Non"
  tr
    th = t(:nom)
    td = @equipier.nom
  tr
    th = t(:prenom)
    td = @equipier.prenom
  tr
    th = t(:photo)
    td = image_tag(@equipier.photo.thumb.url) unless @equipier.photo.file.nil?
  tr
    th = t(:rue)
    td = @equipier.rue
  tr
    th = t(:cp)
    td = @equipier.cp
  tr
    th = t(:ville)
    td = @equipier.ville
  tr
    th = t(:telephone_fixe)
    td = @equipier.telephone_fixe
  tr
    th = t(:telephone_portable)
    td = @equipier.telephone_portable
  tr
    th = t(:email)
    td = @equipier.email
  tr
    th = t(:profession)
    td = @equipier.profession
  tr
    th = t(:date_naissance)
    td = @equipier.date_naissance
  tr
    th = t(:lieu_naissance)
    td = @equipier.lieu_naissance
  tr
    th = t(:nationalite)
    td = @equipier.nationalite
  tr
    th = t(:permis_conduire_num)
    td = @equipier.permis_conduire_num
  tr
    th = t(:permis_conduire)
    td = link_to(image_tag("icone_pdf.png"), @equipier.permis_conduire.url) unless @equipier.permis_conduire.file.nil? || (cannot? :edit, @equipier)
  tr
    th = t(:passeport_num)
    td = @equipier.passeport_num
  tr
    th = t(:passeport)
    td = link_to(image_tag("icone_pdf.png"), @equipier.passeport.url) unless @equipier.passeport.file.nil? || (cannot? :edit, @equipier)
  tr
    th = t(:passeport_date_delivrance)
    td = @equipier.passeport_date_delivrance
  tr
    th = t(:passeport_lieu_delivrance)
    td = @equipier.passeport_lieu_delivrance
  tr
    th = t(:passeport_date_validite)
    td = @equipier.passeport_date_validite
  tr
    th = t(:groupe_sanguin)
    td = @equipier.groupe_sanguin
  tr
    th = t(:nom_prenom_a_prevenir)
    td = @equipier.nom_prenom_a_prevenir
  tr
    th = t(:tel_a_prevenir)
    td = @equipier.tel_a_prevenir
  tr
    th = t(:taille_t_shirt)
    td = @equipier.taille_t_shirt